"""ChromaDB HTTP client wrapper.

Manages two collections:
  • **documents** – ingested personal files (PDF, TXT, MD).
  • **conversations** – embedded chat messages for long-term recall.

Embeddings are generated by calling LiteLLM → Ollama (nomic-embed-text).
This avoids bundling heavy ML libs inside the app container.
"""

from __future__ import annotations

import logging
from typing import Any

import chromadb
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

from config import settings

log = logging.getLogger(__name__)

_client: chromadb.HttpClient | None = None
_documents_col: Any = None
_conversations_col: Any = None


def _embedding_fn() -> OpenAIEmbeddingFunction:
    return OpenAIEmbeddingFunction(
        api_key=settings.litellm_api_key,
        api_base=settings.litellm_base_url,
        model_name=settings.embedding_model,
    )


async def init_store() -> None:
    """Initialise the ChromaDB client and ensure collections exist."""
    global _client, _documents_col, _conversations_col
    _client = chromadb.HttpClient(host=settings.chromadb_host, port=settings.chromadb_port)
    ef = _embedding_fn()
    _documents_col = _client.get_or_create_collection("documents", embedding_function=ef)
    _conversations_col = _client.get_or_create_collection("conversations", embedding_function=ef)
    log.info(
        "ChromaDB ready – documents: %d items, conversations: %d items",
        _documents_col.count(),
        _conversations_col.count(),
    )


# ── Document collection ──────────────────────────


def add_documents(ids: list[str], texts: list[str], metadatas: list[dict] | None = None) -> None:
    assert _documents_col
    _documents_col.add(ids=ids, documents=texts, metadatas=metadatas)


async def search_documents(query: str, top_k: int = 5) -> list[str]:
    """Semantic search over ingested documents. Returns text snippets."""
    assert _documents_col
    results = _documents_col.query(query_texts=[query], n_results=top_k)
    docs = results.get("documents", [[]])[0]
    return docs


# ── Conversation collection ──────────────────────


def add_conversation_message(msg_id: str, text: str, metadata: dict | None = None) -> None:
    assert _conversations_col
    _conversations_col.add(ids=[msg_id], documents=[text], metadatas=[metadata or {}])


async def search_conversations(query: str, top_k: int = 3) -> list[str]:
    """Semantic search over past conversation messages."""
    assert _conversations_col
    if _conversations_col.count() == 0:
        return []
    results = _conversations_col.query(query_texts=[query], n_results=top_k)
    docs = results.get("documents", [[]])[0]
    return docs
