use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: "change-me-to-something-random"
  limiter: false

engines:
  - name: google
    engine: google
    shortcut: g
  - name: bing
    engine: bing
    shortcut: b
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
